### ISSUE TITLE
copy-paste typo?

### ISSUE THREAD

**Issue by rogovsky** [nitroshare/qmdnsengine#3]
void Message::reply(const Message &other)
{
    if (other.port() == MdnsPort) {
        if (other.address().protocol() == QAbstractSocket::IPv4Protocol) {
            setAddress(MdnsIpv4Address);
        } else {
            setAddress(MdnsIpv4Address);   <= "Here should be MdnsIpv6Address????"
        }
    } else {
        setAddress(other.address());
    }
    setPort(other.port());
    setTransactionId(other.transactionId());
    setResponse(true);
}

**Comment by nathan-osman** [comment]
Good catch, thanks!
